name: nebula5_dart_gdbc
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  protobuf: ^4.0.0
  grpc: ^4.0.4
  fixnum: ^1.1.1
  decimal: ^3.0.2
  # dart_gdbc: ^0.0.5
  dart_gdbc: 
    path: ../../

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
